name: Tag and Release Pipeline - Main

on:
  push:
    branches:
      - main
    tags:
      - "*"
   
jobs:
  release:
  
    runs-on: ubuntu-latest
    if: |
          (github.ref == 'refs/heads/main' && github.event_name == 'push' && contains(github.event.head_commit.message, 'skip-ci')) ||
          (github.ref == 'refs/heads/dev' && github.event_name == 'push' && contains(github.event.head_commit.message, 'skip-ci'))
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Echo success message
        run: echo "Repository successfully checked out!"

 
