name: Dev Manual Trigger and release pipeline

on:
  workflow_dispatch:
    branches:
      - dev

jobs:
  release:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Echo success message
        run: echo "Repository successfully checked out!"
