name: Tag and Release Pipeline - Main

on:
  push:
    branches:
      - main
jobs:
  release:
  
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' &&
      endsWith(github.ref, 'refs/tags/') &&
      github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Echo success message
        run: echo "Repository successfully checked out!"

