name: Tag and Release Pipeline - Main

on:
  push:
    tags:
      - "*"
jobs:
  release:
  
    runs-on: ubuntu-latest
    #working#if: github.event_name == 'push' && (github.ref_type == 'tag' || (github.ref == 'refs/heads/main' && startsWith(github.ref, 'refs/tags/')))
    #if: github.event_name == 'push' && github.ref == 'refs/heads/main' && startsWith(github.ref, 'refs/tags/')
     if: |
          github.event_name == 'push' &&
          startsWith(github.ref, 'refs/tags/') &&
          github.ref == 'refs/tags/' + env.TAG_NAME
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Echo success message
        run: echo "Repository successfully checked out!"

