name: Tag and Release Pipeline - Main

on:
  push:
    branches:
      - main
    tags:
      - "*"
   
jobs:
  release:
  
    runs-on: ubuntu-latest
    if: github.ref == 'refs/tags/*'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Echo success message
        run: echo "Repository successfully checked out!"

 
