name: Tag and Release Pipeline - Main

on:
  push:
    branches:
      - main
    tags:
      - "*"
   
jobs:
  release:
  
    runs-on: ubuntu-latest
    if: |
          github.event_name == 'push' && (
            github.ref == 'refs/heads/main' ||
            github.ref == 'refs/heads/dev' && contains(github.event.head_commit.message, 'skip-ci')
          )
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Echo success message
        run: echo "Repository successfully checked out!"

 
