name: Tag and Release Pipeline - Main

on:
  push:
    tags:
      - "*"
    branches:
      - main  
jobs:
  release:
  
    runs-on: ubuntu-latest
    #if: github.event_name == 'push' && github.ref == 'refs/tags/*'
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Echo success message
        run: echo "Repository successfully checked out!"

